# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=9)),
                ('fname', models.CharField(max_length=60)),
                ('mname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
                ('sex', models.CharField(max_length=6)),
                ('addressHome', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
